INSERT INTO `api_user`
(`id`,
`name`,
`email`,
`username`,
`password`,
`account_non_expired`,
`account_non_locked`,
`credentials_non_expired`,
`inactive`)
VALUES
(1,
'Administrativo Manager',
'adm@manager.com',
'adm@manager.com',
'$2a$10$TB5c10nvYGJ5Ry4Asx.VkugG8k0CZv5xN9k7xWoQyZajl2nQrHeUK',
1,
1,
1,
0),
(2,
'Data Collector API',
'datacolector@manager.com',
'datacolector@manager.com',
'$2a$10$xjzjhLCStH97jNvSs6K.hOOMFUEpHGdhMvm3WiPt2Q4Mz9Bx9RlD.',
1,
1,
1,
0);