drop table if exists `manager`.`bank`;

CREATE TABLE `manager`.`bank` 
(
	id VARCHAR(10) NOT NULL,
    description varchar(100) NOT NULL,
	inactive BIT NOT NULL,
    user_creation BIGINT NOT NULL,
    creation_date DATETIME NOT NULL,
    user_change BIGINT NOT NULL,
    change_date DATETIME NOT NULL,
    PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `manager`.`bank`  select '001','001 - BANCO DO BRASIL S/A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '002','002 - BANCO CENTRAL DO BRASIL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '003','003 - BANCO DA AMAZONIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '004','004 - BANCO DO NORDESTE DO BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '007','007 - BANCO NAC DESENV. ECO. SOCIAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '008','008 - BANCO MERIDIONAL DO BRASIL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '020','020 - BANCO DO ESTADO DE ALAGOAS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '021','021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '022','022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '024','024 - BANCO DO ESTADO DE PERNAMBUCO', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '025','025 - BANCO ALFA S/A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '026','026 - BANCO DO ESTADO DO ACRE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '027','027 - BANCO DO ESTADO DE SANTA CATARINA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '028','028 - BANCO DO ESTADO DA BAHIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '029','029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '030','030 - BANCO DO ESTADO DA PARAIBA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '031','031 - BANCO DO ESTADO DE GOIAS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '032','032 - BANCO DO ESTADO DO MATO GROSSO S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '033','033 - BANCO DO ESTADO DE SAO PAULO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '034','034 - BANCO DO ESADO DO AMAZONAS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '035','035 - BANCO DO ESTADO DO CEARA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '036','036 - BANCO DO ESTADO DO MARANHAO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '037','037 - BANCO DO ESTADO DO PARA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '038','038 - BANCO DO ESTADO DO PARANA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '039','039 - BANCO DO ESTADO DO PIAUI S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '041','041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '047','047 - BANCO DO ESTADO DE SERGIPE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '048','048 - BANCO DO ESTADO DE MINAS GERAIS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '059','059 - BANCO DO ESTADO DE RONDONIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '070','070 - BANCO DE BRASILIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '104','104 - CAIXA ECONOMICA FEDERAL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '106','106 - BANCO ITABANCO S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '107','107 - BANCO BBM S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '109','109 - BANCO CREDIBANCO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '116','116 - BANCO B.N.L DO BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '148','148 - MULTI BANCO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '151','151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '153','153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '165','165 - BANCO NORCHEM S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '166','166 - BANCO INTER-ATLANTICO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '168','168 - BANCO C.C.F. BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '175','175 - CONTINENTAL BANCO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '184','184 - BBA - CREDITANSTALT S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '199','199 - BANCO FINANCIAL PORTUGUES', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '200','200 - BANCO FRICRISA AXELRUD S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '201','201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '204','204 - BANCO S.R.L S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '205','205 - BANCO SUL AMERICA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '206','206 - BANCO MARTINELLI S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '208','208 - BANCO PACTUAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '210','210 - DEUTSCH SUDAMERIKANICHE BANK AG', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '211','211 - BANCO SISTEMA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '212','212 - BANCO MATONE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '213','213 - BANCO ARBI S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '214','214 - BANCO DIBENS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '215','215 - BANCO AMERICA DO SUL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '216','216 - BANCO REGIONAL MALCON S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '217','217 - BANCO AGROINVEST S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '218','218 - BBS - BANCO BONSUCESSO S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '219','219 - BANCO DE CREDITO DE SAO PAULO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '220','220 - BANCO CREFISUL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '221','221 - BANCO GRAPHUS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '222','222 - BANCO AGF BRASIL S. A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '223','223 - BANCO INTERUNION S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '224','224 - BANCO FIBRA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '225','225 - BANCO BRASCAN S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '228','228 - BANCO ICATU S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '229','229 - BANCO CRUZEIRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '230','230 - BANCO BANDEIRANTES S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '231','231 - BANCO BOAVISTA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '232','232 - BANCO INTERPART S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '233','233 - BANCO MAPPIN S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '234','234 - BANCO LAVRA S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '235','235 - BANCO LIBERAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '236','236 - BANCO CAMBIAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '237','237 - BANCO BRADESCO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '239','239 - BANCO BANCRED S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '240','240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '241','241 - BANCO CLASSICO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '242','242 - BANCO EUROINVEST S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '243','243 - BANCO STOCK S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '244','244 - BANCO CIDADE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '245','245 - BANCO EMPRESARIAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '246','246 - BANCO ABC ROMA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '247','247 - BANCO OMEGA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '249','249 - BANCO INVESTCRED S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '250','250 - BANCO SCHAHIN CURY S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '251','251 - BANCO SAO JORGE S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '252','252 - BANCO FININVEST S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '254','254 - BANCO PARANA BANCO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '255','255 - MILBANCO S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '256','256 - BANCO GULVINVEST S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '258','258 - BANCO INDUSCRED S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '261','261 - BANCO VARIG S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '262','262 - BANCO BOREAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '263','263 - BANCO CACIQUE', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '264','264 - BANCO PERFORMANCE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '265','265 - BANCO FATOR S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '266','266 - BANCO CEDULA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '267','267 - BANCO BBM-COM.C.IMOB.CFI S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '275','275 - BANCO REAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '277','277 - BANCO PLANIBANC S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '282','282 - BANCO BRASILEIRO COMERCIAL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '291','291 - BANCO DE CREDITO NACIONAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '294','294 - BCR - BANCO DE CREDITO REAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '295','295 - BANCO CREDIPLAN S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '300','300 - BANCO DE LA NACION ARGENTINA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '302','302 - BANCO DO PROGRESSO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '303','303 - BANCO HNF S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '304','304 - BANCO PONTUAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '308','308 - BANCO COMERCIAL BANCESA S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '318','318 - BANCO B.M.G. S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '320','320 - BANCO INDUSTRIAL E COMERCIAL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '341','341 - BANCO ITAU S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '346','346 - BANCO FRANCES E BRASILEIRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '347','347 - BANCO SUDAMERIS BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '351','351 - BANCO BOZANO SIMONSEN S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '353','353 - BANCO GERAL DO COMERCIO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '356','356 - ABN AMRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '366','366 - BANCO SOGERAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '369','369 - PONTUAL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '370','370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '372','372 - BANCO ITAMARATI S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '375','375 - BANCO FENICIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '376','376 - CHASE MANHATTAN BANK S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '388','388 - BANCO MERCANTIL DE DESCONTOS S/A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '389','389 - BANCO MERCANTIL DO BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '392','392 - BANCO MERCANTIL DE SAO PAULO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '394','394 - BANCO B.M.C. S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '399','399 - BANCO BAMERINDUS DO BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '409','409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '412','412 - BANCO NACIONAL DA BAHIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '415','415 - BANCO NACIONAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '420','420 - BANCO NACIONAL DO NORTE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '422','422 - BANCO SAFRA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '424','424 - BANCO NOROESTE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '434','434 - BANCO FORTALEZA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '453','453 - BANCO RURAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '456','456 - BANCO TOKIO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '464','464 - BANCO SUMITOMO BRASILEIRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '466','466 - BANCO MITSUBISHI BRASILEIRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '472','472 - LLOYDS BANK PLC', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '473','473 - BANCO FINANCIAL PORTUGUES S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '477','477 - CITIBANK N.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '479','479 - BANCO DE BOSTON S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '480','480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '483','483 - BANCO AGRIMISA S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '487','487 - DEUTSCHE BANK S.A - BANCO ALEMAO', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '488','488 - BANCO J. P. MORGAN S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '489','489 - BANESTO BANCO URUGAUAY S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '492','492 - INTERNATIONALE NEDERLANDEN BANK N.V.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '493','493 - BANCO UNION S.A.C.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '494','494 - BANCO LA REP. ORIENTAL DEL URUGUAY', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '495','495 - BANCO LA PROVINCIA DE BUENOS AIRES', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '496','496 - BANCO EXTERIOR DE ESPANA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '498','498 - CENTRO HISPANO BANCO', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '499','499 - BANCO IOCHPE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '501','501 - BANCO BRASILEIRO IRAQUIANO S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '502','502 - BANCO SANTANDER S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '504','504 - BANCO MULTIPLIC S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '505','505 - BANCO GARANTIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '600','600 - BANCO LUSO BRASILEIRO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '601','601 - BFC BANCO S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '602','602 - BANCO PATENTE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '604','604 - BANCO INDUSTRIAL DO BRASIL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '607','607 - BANCO SANTOS NEVES S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '608','608 - BANCO OPEN S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '610','610 - BANCO V.R. S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '611','611 - BANCO PAULISTA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '612','612 - BANCO GUANABARA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '613','613 - BANCO PECUNIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '616','616 - BANCO INTERPACIFICO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '617','617 - BANCO INVESTOR S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '618','618 - BANCO TENDENCIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '621','621 - BANCO APLICAP S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '622','622 - BANCO DRACMA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '623','623 - BANCO PANAMERICANO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '624','624 - BANCO GENERAL MOTORS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '625','625 - BANCO ARAUCARIA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '626','626 - BANCO FICSA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '627','627 - BANCO DESTAK S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '628','628 - BANCO CRITERIUM S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '629','629 - BANCORP BANCO COML. E. DE INVESTMENTO', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '630','630 - BANCO INTERCAP S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '633','633 - BANCO REDIMENTO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '634','634 - BANCO TRIANGULO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '635','635 - BANCO DO ESTADO DO AMAPA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '637','637 - BANCO SOFISA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '638','638 - BANCO PROSPER S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '639','639 - BIG S.A. - BANCO IRMAOS GUIMARAES', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '640','640 - BANCO DE CREDITO METROPOLITANO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '641','641 - BANCO EXCEL ECONOMICO S/A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '643','643 - BANCO SEGMENTO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '645','645 - BANCO DO ESTADO DE RORAIMA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '647','647 - BANCO MARKA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '648','648 - BANCO ATLANTIS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '649','649 - BANCO DIMENSAO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '650','650 - BANCO PEBB S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '652','652 - BANCO FRANCES E BRASILEIRO SA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '653','653 - BANCO INDUSVAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '654','654 - BANCO A. J. RENNER S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '655','655 - BANCO VOTORANTIM S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '656','656 - BANCO MATRIX S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '657','657 - BANCO TECNICORP S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '658','658 - BANCO PORTO REAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '702','702 - BANCO SANTOS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '705','705 - BANCO INVESTCORP S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '707','707 - BANCO DAYCOVAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '711','711 - BANCO VETOR S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '713','713 - BANCO CINDAM S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '715','715 - BANCO VEGA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '718','718 - BANCO OPERADOR S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '719','719 - BANCO PRIMUS S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '720','720 - BANCO MAXINVEST S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '721','721 - BANCO CREDIBEL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '722','722 - BANCO INTERIOR DE SAO PAULO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '724','724 - BANCO PORTO SEGURO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '725','725 - BANCO FINABANCO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '726','726 - BANCO UNIVERSAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '728','728 - BANCO FITAL S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '729','729 - BANCO FONTE S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '730','730 - BANCO COMERCIAL PARAGUAYO S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '731','731 - BANCO GNPP S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '732','732 - BANCO PREMIER S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '733','733 - BANCO NACOES S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '734','734 - BANCO GERDAU S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '735','735 - BACO POTENCIAL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '736','736 - BANCO UNITED S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '737','737 - THECA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '738','738 - MARADA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '739','739 - BGN', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '740','740 - BCN BARCLAYS', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '741','741 - BRP', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '742','742 - EQUATORIAL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '743','743 - BANCO EMBLEMA S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '744','744 - THE FIRST NATIONAL BANK OF BOSTON', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '745','745 - CITIBAN N.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '746','746 - MODAL S\A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '747','747 - RAIBOBANK DO BRASIL', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '748','748 - SICREDI', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '749','749 - BRMSANTIL SA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '750','750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '751','751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '752','752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '753','753 - BANCO COMERCIAL URUGUAI S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '755','755 - BANCO MERRILL LYNCH S.A', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '756','756 - BANCO COOPERATIVO DO BRASIL S.A.', 0, 1, now(), 1, now();
INSERT INTO `manager`.`bank`  select '757','757 - BANCO KEB DO BRASIL S.A.', 0, 1, now(), 1, now();